/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import Mathlib.LinearAlgebra.Matrix.Circulant
import Mathlib.Data.ZMod.Basic
import Mathlib.Analysis.Matrix.Normed

/-!
# The block covariance matrix `S^(B)` on `Z_L^2`

Formalization of the two-dimensional random band matrix paper, Section 2.1 and
Section 8 (`8_theta_properties.tex`).

The paper sets, for `a b : Z_L^2`,
`S^(B)_{ab} = (1/5) * 1(|a - b|_L ≤ 1)`,
the transition matrix of the lazy nearest-neighbour random walk on the discrete
torus `Z_L^2`.  Since `|a - b|_L ≤ 1` means exactly
`a - b ∈ {(0,0), (±1,0), (0,±1)}`, this is the circulant matrix on the group
`ZMod L × ZMod L` generated by `RBM.sbKernel`.

`S^(B)` is stochastic only when `3 ≤ L`: for `L = 1, 2` the five lattice points
above are not distinct.  The paper leaves this implicit; here `3 ≤ L` is carried
as an explicit hypothesis.  See `docs/paper-deltas.md`.

## Main results

* `RBM.SB_isSymm`          : symmetry, Lemma `lem_propTH` (1) at the level of `S^(B)`
* `RBM.SB_apply_add_right` : translation invariance, Lemma `lem_propTH` (2)
* `RBM.card_sbSupport`     : the five lattice points are distinct for `3 ≤ L`
* `RBM.sum_SB_row`         : the rows of `S^(B)` sum to `1`
* `RBM.SB_mulVec_one`      : `S^(B) 1 = 1`
-/

namespace RBM

open Finset Matrix

/-- The index set of the paper: the discrete torus `Z_L^2`. -/
abbrev Z2 (L : ℕ) := ZMod L × ZMod L

section Defs

variable (L : ℕ)

/-- The nearest-neighbour support `{(0,0), (1,0), (-1,0), (0,1), (0,-1)} ⊆ Z_L^2`. -/
def sbSupport : Finset (Z2 L) := {(0, 0), (1, 0), (-1, 0), (0, 1), (0, -1)}

/-- The generating kernel of `S^(B)`: the value `1/5` on the five-point
nearest-neighbour support, zero elsewhere. -/
noncomputable def sbKernel : Z2 L → ℂ :=
  fun u => if u ∈ sbSupport L then (5 : ℂ)⁻¹ else 0

/-- The block covariance matrix `S^(B)` of Section 2.1, on `Z_L^2`. -/
noncomputable def SB : Matrix (Z2 L) (Z2 L) ℂ := circulant (sbKernel L)

theorem SB_apply (a b : Z2 L) : SB L a b = sbKernel L (a - b) := rfl

end Defs

section Char

variable (L : ℕ)

theorem one_ne_zero_zmod (hL : 3 ≤ L) : (1 : ZMod L) ≠ 0 := by
  have h : ((1 : ℕ) : ZMod L) ≠ 0 := by
    rw [Ne, CharP.cast_eq_zero_iff (ZMod L) L 1]
    intro hdvd
    have := Nat.le_of_dvd Nat.one_pos hdvd
    omega
  simpa using h

theorem two_ne_zero_zmod (hL : 3 ≤ L) : (2 : ZMod L) ≠ 0 := by
  have h : ((2 : ℕ) : ZMod L) ≠ 0 := by
    rw [Ne, CharP.cast_eq_zero_iff (ZMod L) L 2]
    intro hdvd
    have := Nat.le_of_dvd (by norm_num) hdvd
    omega
  simpa using h

/-- `1 ≠ -1` in `ZMod L` for `3 ≤ L`: this is what makes the five lattice points
of `sbSupport` distinct. -/
theorem one_ne_neg_one_zmod (hL : 3 ≤ L) : (1 : ZMod L) ≠ -1 := fun h =>
  two_ne_zero_zmod L hL (by linear_combination h)

theorem zero_ne_one_zmod (hL : 3 ≤ L) : (0 : ZMod L) ≠ 1 :=
  Ne.symm (one_ne_zero_zmod L hL)

theorem zero_ne_neg_one_zmod (hL : 3 ≤ L) : (0 : ZMod L) ≠ -1 := fun h =>
  one_ne_zero_zmod L hL (by linear_combination -h)

end Char

section Symmetry

variable (L : ℕ)

theorem neg_mem_sbSupport {u : Z2 L} : -u ∈ sbSupport L ↔ u ∈ sbSupport L := by
  obtain ⟨u₁, u₂⟩ := u
  simp only [sbSupport, Finset.mem_insert, Finset.mem_singleton, Prod.neg_mk, Prod.mk.injEq,
    neg_eq_iff_eq_neg, neg_zero, neg_neg]
  tauto

theorem sbKernel_neg (u : Z2 L) : sbKernel L (-u) = sbKernel L u := by
  simp only [sbKernel]
  exact if_congr (neg_mem_sbSupport L) rfl rfl

/-- Lemma `lem_propTH` (1) at the level of `S^(B)`: symmetry. -/
theorem SB_isSymm : (SB L).IsSymm := by
  rw [SB, circulant_isSymm_iff]
  exact sbKernel_neg L

theorem SB_transpose : (SB L)ᵀ = SB L := SB_isSymm L

/-- Lemma `lem_propTH` (2) at the level of `S^(B)`: translation invariance. -/
theorem SB_apply_add_right (a b c : Z2 L) : SB L (a + c) (b + c) = SB L a b := by
  simp only [SB_apply, add_sub_add_right_eq_sub]

end Symmetry

section Support

variable (L : ℕ)

/-- For `3 ≤ L` the five lattice points of the nearest-neighbour support are
distinct. -/
theorem card_sbSupport (hL : 3 ≤ L) : (sbSupport L).card = 5 := by
  have h01 : (0 : ZMod L) ≠ 1 := zero_ne_one_zmod L hL
  have h0m : (0 : ZMod L) ≠ -1 := zero_ne_neg_one_zmod L hL
  have h1m : (1 : ZMod L) ≠ -1 := one_ne_neg_one_zmod L hL
  rw [sbSupport,
    Finset.card_insert_of_notMem (by simp [Prod.ext_iff, h01, h0m, h01.symm, h0m.symm]),
    Finset.card_insert_of_notMem (by simp [Prod.ext_iff, h1m, h01, h0m, h01.symm, h0m.symm]),
    Finset.card_insert_of_notMem (by simp [Prod.ext_iff, h0m, h0m.symm, h01, h01.symm]),
    Finset.card_insert_of_notMem (by simp [Prod.ext_iff, h1m]),
    Finset.card_singleton]

/-- A sum over the five-point support, written out. -/
theorem sum_over_sbSupport (hL : 3 ≤ L) (f : Z2 L → ℂ) :
    ∑ v ∈ sbSupport L, f v
      = f (0, 0) + f (1, 0) + f (-1, 0) + f (0, 1) + f (0, -1) := by
  have h01 : (0 : ZMod L) ≠ 1 := zero_ne_one_zmod L hL
  have h0m : (0 : ZMod L) ≠ -1 := zero_ne_neg_one_zmod L hL
  have h1m : (1 : ZMod L) ≠ -1 := one_ne_neg_one_zmod L hL
  rw [sbSupport,
    Finset.sum_insert (by simp [Prod.ext_iff, h01, h0m, h01.symm, h0m.symm]),
    Finset.sum_insert (by simp [Prod.ext_iff, h1m, h01, h0m, h01.symm, h0m.symm]),
    Finset.sum_insert (by simp [Prod.ext_iff, h0m, h0m.symm, h01, h01.symm]),
    Finset.sum_insert (by simp [Prod.ext_iff, h1m]),
    Finset.sum_singleton]
  ring

end Support

section Stochastic

variable (L : ℕ) [NeZero L]

/-- Total mass of the generating kernel is `1`, for `3 ≤ L`. -/
theorem sum_sbKernel (hL : 3 ≤ L) : ∑ u : Z2 L, sbKernel L u = 1 := by
  classical
  simp only [sbKernel]
  rw [Finset.sum_ite_mem, Finset.univ_inter, Finset.sum_const, card_sbSupport L hL]
  norm_num

/-- Each row of `S^(B)` sums to `1`. -/
theorem sum_SB_row (hL : 3 ≤ L) (a : Z2 L) : ∑ b : Z2 L, SB L a b = 1 := by
  have h : ∑ b : Z2 L, SB L a b = ∑ u : Z2 L, sbKernel L u := by
    refine Fintype.sum_equiv (Equiv.subLeft a) _ _ ?_
    intro b
    simp [SB_apply]
  rw [h, sum_sbKernel L hL]

/-- `S^(B) 1 = 1`: `S^(B)` is stochastic. -/
theorem SB_mulVec_one (hL : 3 ≤ L) : SB L *ᵥ (1 : Z2 L → ℂ) = 1 := by
  funext a
  simp only [Matrix.mulVec, dotProduct, Pi.one_apply, mul_one]
  exact sum_SB_row L hL a

end Stochastic

end RBM
