import RBM2D.Basic
import RBM2D.Test.Axioms
import RBM2D.Defs.Block
import RBM2D.Defs.Dist
import RBM2D.Defs.Domination
import RBM2D.Defs.Model
import RBM2D.Defs.StochDom
import RBM2D.Propagator.Basic
import RBM2D.Propagator.Bounds
import RBM2D.Propagator.Symbol
import RBM2D.Propagator.Elliptic
import RBM2D.Propagator.Momentum
import RBM2D.Propagator.Shells
import RBM2D.Propagator.GeomSum
import RBM2D.Propagator.Dyadic
import RBM2D.Propagator.ZeroMode
import RBM2D.Propagator.Harmonic
import RBM2D.Propagator.LatticeSum
import RBM2D.Propagator.LogIntegral
import RBM2D.Propagator.ContinuumSymbol
import RBM2D.Propagator.Deriv
import RBM2D.Propagator.Contour
import RBM2D.Propagator.Decay
import RBM2D.Propagator.Cutoff
import RBM2D.Propagator.AbelSum
import RBM2D.Propagator.SymbolDiff
import RBM2D.Propagator.SymbolReciprocalDiff
import RBM2D.Propagator.SymbolShiftAnnulus
import RBM2D.Propagator.PeriodizeShells
import RBM2D.Propagator.PeriodizeTail
import RBM2D.Propagator.PeriodizeConvergence
import RBM2D.Propagator.PeriodizeShift
import RBM2D.Propagator.PeriodizeDescend
import RBM2D.Propagator.PeriodizeStencil
import RBM2D.Propagator.PeriodizeDelta
import RBM2D.Propagator.PeriodizeTorusStencil
import RBM2D.Propagator.PeriodizeResolventBridge
import RBM2D.Propagator.PeriodizeFourierDelta
import RBM2D.Propagator.PeriodizeIntegrand
import RBM2D.Propagator.FiniteDiff
import RBM2D.Propagator.DerivBounds
import RBM2D.Delocalization
import RBM2D.Gauss.Envelope
import RBM2D.Gauss.Stein
import RBM2D.Gauss.SteinMatrix
import RBM2D.Gauss.Model
import RBM2D.Gauss.Domination
import RBM2D.Gauss.MomentBridge
import RBM2D.Gauss.FlowTimeCont
import RBM2D.Gauss.GreenTimeCont
import RBM2D.Gauss.LoopTimeCont
import RBM2D.Gauss.LoopSampleCont
import RBM2D.Gauss.LoopEnvelope
import RBM2D.Gauss.SpectralWindow
import RBM2D.Gauss.SpectralAlgebra
import RBM2D.Gauss.SpectralDerivative
import RBM2D.Gauss.GreenDerivative
import RBM2D.Gauss.LoopDerivative
import RBM2D.Gauss.LoopCoordinateDerivative
import RBM2D.Gauss.GreenCoordinateSecondDerivative
import RBM2D.Gauss.LoopCoordinateSecondDerivative
import RBM2D.Gauss.LoopCoordinateDerivativeBounds
import RBM2D.Gauss.LoopCoordinateIntegrability
import RBM2D.Gauss.LoopFlowCoordinateChain
import RBM2D.Gauss.LoopFlowSteinExpectation
import RBM2D.Gauss.LoopFlowDerivativeEnvelope
import RBM2D.Gauss.LoopExpectationDerivative
import RBM2D.Gauss.LoopSpectralDriftCuts
import RBM2D.Gauss.LoopGeneratorSamplewise
import RBM2D.Gauss.LoopGeneratorExpectation
import RBM2D.Gauss.LoopInitialValue
import RBM2D.Gauss.LoopInitialValueScalar
import RBM2D.Gauss.LoopInitialValueProjectionWords
import RBM2D.Gauss.LoopInitialValueSupport
import RBM2D.Hierarchy.Loops
import RBM2D.Hierarchy.WardResolvent
import RBM2D.Hierarchy.Operations
import RBM2D.Hierarchy.OperationsPair
import RBM2D.Hierarchy.OperationsPairWord
import RBM2D.Hierarchy.ContractionBasic
import RBM2D.Hierarchy.ContractionDirections
import RBM2D.Hierarchy.ContractionSum
import RBM2D.Hierarchy.ContractionUnused
import RBM2D.Hierarchy.ContractionCutWords
import RBM2D.Hierarchy.ContractionDrift
import RBM2D.Hierarchy.ContractionSecondLoop
import RBM2D.Hierarchy.ContractionSecondLoopSameEdge
import RBM2D.Hierarchy.ContractionSecondLoopSameEdgeWord
import RBM2D.Hierarchy.ContractionSecondLoopSameEdgeCut
import RBM2D.Hierarchy.ContractionEdgeSplits
import RBM2D.Hierarchy.ContractionPairSplits
import RBM2D.Hierarchy.ContractionFirstDerivativePositionSum
import RBM2D.Hierarchy.ContractionSecondDerivativePositionSum
import RBM2D.Hierarchy.ContractionSecondDerivativeTraceSum
import RBM2D.Hierarchy.ContractionPositionLoopBridge
import RBM2D.Hierarchy.ContractionSameEdgePositionCut
import RBM2D.Hierarchy.ContractionPairPositionCut
import RBM2D.Hierarchy.ContractionSecondLoopAllCuts
import RBM2D.Hierarchy.LoopHierarchyCutContinuity
import RBM2D.Hierarchy.LoopHierarchyCutBlockSumBound
import RBM2D.Propagator.KinfSwap
import RBM2D.Propagator.PeriodizeImageSum
import RBM2D.Propagator.ShellCutoff
import RBM2D.Propagator.KinfBoundFirst
import RBM2D.Propagator.InvSymbolDiff
import RBM2D.Propagator.KinfBound
import RBM2D.Propagator.ShellCutoffDiff
import RBM2D.Propagator.ShellSBP
import RBM2D.Propagator.PeriodizeKinfSummable
import RBM2D.Defs.Semicircle
import RBM2D.Propagator.DecayLarge
import RBM2D.Defs.SemicircleIntegral
import RBM2D.Propagator.ShellKernelBound
import RBM2D.Propagator.Prop5
import RBM2D.Propagator.ShellKernelFD
import RBM2D.Propagator.Prop6
import RBM2D.Loop.Kcal
import RBM2D.Path.PerTime
import RBM2D.Path.Walk
import RBM2D.Path.Azuma
import RBM2D.Path.Scales
import RBM2D.Path.Kernel
import RBM2D.Gauss.LinearForm
import RBM2D.Loop.Molecule
import RBM2D.Loop.LatticeCount
import RBM2D.Loop.TreeRep
import RBM2D.Loop.PropHyp
import RBM2D.Loop.PureLoop
import RBM2D.Path.Step2Props
import RBM2D.Path.Stop
import RBM2D.Loop.SumZero
import RBM2D.Path.ScalesBridge
import RBM2D.Loop.Unique
import RBM2D.Loop.KBoundCut
import RBM2D.Path.Markov
import RBM2D.Loop.Cyclic
import RBM2D.Induction.Split
import RBM2D.Induction.PerTimeCalc
import RBM2D.Path.UBounds
import RBM2D.Path.TailSums
import RBM2D.Loop.Ward
import RBM2D.Path.DriftLip
import RBM2D.Induction.Defs
import RBM2D.Loop.SumAll
import RBM2D.Path.OneStep
import RBM2D.Path.Step2Vocab
import RBM2D.Path.Transfer
import RBM2D.Induction.ConArgDet
import RBM2D.Evolution.LatticeSums
import RBM2D.Loop.SumZeroWard
import RBM2D.Evolution.XiBounds
import RBM2D.Path.LoopStep
import RBM2D.Evolution.Defs
import RBM2D.Induction.ScaleFacts
import RBM2D.Path.KellStar
import RBM2D.Induction.ConArg
import RBM2D.Green.Pins
import RBM2D.Path.UTransport
import RBM2D.Green.Minor
import RBM2D.Loop.KBoundEmpty
import RBM2D.Induction.Continuity
import RBM2D.Path.DriftAlgebra
import RBM2D.Loop.KBoundInner
import RBM2D.Evolution.KernelExpand
import RBM2D.Path.Step2PropsV3
import RBM2D.Induction.Step2TargetV3
import RBM2D.Evolution.Step61
import RBM2D.Green.EntryCore
import RBM2D.Induction.Step3
import RBM2D.Loop.KBound
import RBM2D.Path.StepDecomp
import RBM2D.Induction.Step1
import RBM2D.Green.Stability
import RBM2D.Induction.Step45
import RBM2D.Path.QVForm
import RBM2D.Path.GoodSet
import RBM2D.Path.StepDecompLoop
import RBM2D.Evolution.Case4
import RBM2D.Green.RowIndep
import RBM2D.Path.StepArith
import RBM2D.Path.TimeSums
import RBM2D.Path.QVIdentity
import RBM2D.Induction.Chain
import RBM2D.Endpoints
import RBM2D.Path.Expansion
import RBM2D.Green.EntryBlock
import RBM2D.Green.CondRow
import RBM2D.Path.LemDecCalE
import RBM2D.Evolution.Case5
import RBM2D.Path.DuhamelTail
import RBM2D.Main.DecolFromLocal
import RBM2D.Green.EntryDom
import RBM2D.Evolution.Bridge
import RBM2D.Path.LemDecCalEwG
import RBM2D.Path.LemDecCalEdif
import RBM2D.Green.LDE
import RBM2D.Path.DriftPoint
import RBM2D.Main.QUEFromQDiff
import RBM2D.Path.GoodEvent
import RBM2D.Evolution.Case3Defs
import RBM2D.Green.LDEQuad
import RBM2D.Green.IBPPoly
import RBM2D.Green.LDEQuadMom
import RBM2D.Green.LDEQuadT
import RBM2D.Evolution.CltMoments
import RBM2D.Evolution.FarEntry
import RBM2D.Green.LDEQuadInst
import RBM2D.Path.GoodEventGrid
import RBM2D.Green.EntryGauss
import RBM2D.Path.GoodEventClose
import RBM2D.Path.Bootstrap
import RBM2D.Induction.HierVocab
import RBM2D.Evolution.CltSwap
import RBM2D.Evolution.CltGood
import RBM2D.Evolution.CltResolvent
import RBM2D.Induction.LoopGenN
import RBM2D.Induction.HierAlgebra
import RBM2D.Evolution.CltPath
import RBM2D.Induction.GridDuhamelN
import RBM2D.Green.AvgPins
import RBM2D.Green.GreenDeriv
import RBM2D.Green.FlucVanish
import RBM2D.Induction.HierarchyN
import RBM2D.Path.Step2Local
import RBM2D.Induction.BcalEDecay
import RBM2D.Evolution.CltStep
import RBM2D.Green.FlucAvg
import RBM2D.Green.LocalLaw
import RBM2D.Evolution.CltDecorrelation
import RBM2D.Path.StepBound
import RBM2D.Induction.GridDriftN
import RBM2D.Induction.QVN
import RBM2D.Green.FlucIter
import RBM2D.Green.IBP
import RBM2D.Path.Step2Grid
import RBM2D.Induction.BcalE
import RBM2D.Green.FlucIterHigh
import RBM2D.Green.MinorGoodLe
import RBM2D.Path.Step2Close
import RBM2D.Green.CondDom
import RBM2D.Green.CondStable
import RBM2D.Green.MinorDiff
import RBM2D.Induction.SumZeroQ
import RBM2D.Induction.QopBounds
import RBM2D.Evolution.Case3
import RBM2D.Green.IBPRem
import RBM2D.Induction.KcalDecay
import RBM2D.Induction.DecayLoop
import RBM2D.Green.MinorDiffCond
import RBM2D.Green.Eq45Small
import RBM2D.Green.FlucThreshold
import RBM2D.Induction.GridGoodN
import RBM2D.Induction.LoopC2N
import RBM2D.Induction.B45
import RBM2D.Induction.GridAssemblyN
import RBM2D.Green.FlucAvgDet
import RBM2D.Green.IBPDet
import RBM2D.Green.GbEXP
import RBM2D.Induction.GridGoodEvent
import RBM2D.Evolution.MLExpVocab
import RBM2D.Induction.StepDecompN
import RBM2D.Induction.GridEnvelopeN
import RBM2D.Evolution.MLExpDrift
import RBM2D.Induction.AzumaProxyN
import RBM2D.Evolution.MLExpInv
import RBM2D.Evolution.MLExpHier
import RBM2D.Evolution.MLExpQ
import RBM2D.Evolution.MLExpDuhamel
import RBM2D.Induction.StoppedEndDefs
import RBM2D.Universality.Pins
import RBM2D.Universality.OU
import RBM2D.Induction.MainInd
import RBM2D.Induction.PPVocab
import RBM2D.Induction.AltSymm
import RBM2D.Induction.AltGridQ
import RBM2D.Induction.PPGoodEvent
import RBM2D.Induction.PPDrift
import RBM2D.Induction.NonAltGood
import RBM2D.Induction.PPClosure
import RBM2D.Induction.LocalFormCalc
import RBM2D.Induction.AltProxyQ
import RBM2D.Induction.PPKernel
import RBM2D.Induction.NonAltBudget
import RBM2D.Induction.LocalFormLin
import RBM2D.Induction.PPCondVar
import RBM2D.Induction.LocalFormCuts
import RBM2D.Induction.NonAltEnd
import RBM2D.Universality.EigenMeasurable
import RBM2D.Universality.EigenInterlacing
import RBM2D.Universality.InjSum
import RBM2D.Universality.PoissonSmoothing
import RBM2D.Universality.GUEInvariance
import RBM2D.Universality.FreeConv
import RBM2D.Universality.FreeConvStability
import RBM2D.Universality.Apriori
import RBM2D.Induction.AltDriftQ
import RBM2D.Universality.Step1Cond
import RBM2D.Induction.AltBudgetTerms
import RBM2D.Universality.GreenCorr
import RBM2D.Universality.Step1RegularityA
import RBM2D.Universality.Step1RegularityB
import RBM2D.Universality.UnivMain
import RBM2D.Universality.OUHessian
import RBM2D.Universality.JakSpectral
import RBM2D.Universality.OUGenerator
import RBM2D.Universality.Step1Band
import RBM2D.Universality.JakKernel
import RBM2D.Universality.ZeroModeProfile
import RBM2D.Universality.OUContraction
import RBM2D.Universality.Jak
import RBM2D.Universality.QUEFlow
import RBM2D.Universality.EMCTE2
import RBM2D.Induction.AltEndCompose
import RBM2D.Induction.AltEnd
import RBM2D.Universality.UywKernel
import RBM2D.Induction.AltLevelsQ0
import RBM2D.Induction.AltLevelsQ
import RBM2D.Induction.AltBudget
import RBM2D.Induction.AltAbsorb
import RBM2D.Universality.Uyw
import RBM2D.Main.P7FromSTO
import RBM2D.Main.ZRescale
import RBM2D.Main.EndpointsFromSTO
import RBM2D.Induction.AltLevelsE
import RBM2D.Main.Endpoints
import RBM2D.Universality.GUEPhase.Bootstrap
import RBM2D.Universality.GUELocalBootstrap
import RBM2D.Universality.GUEPhase.AuxCarrier
import RBM2D.Universality.GUEPhase.Grid
import RBM2D.Universality.GUEPhase.Markov
import RBM2D.Universality.GUEPhase.EntryDet
import RBM2D.Universality.GUELocalSchur
import RBM2D.Universality.GUEPhase.KPrim
import RBM2D.Universality.GUEPhase.Generator
import RBM2D.Universality.GUEPhase.OneLoop
import RBM2D.Universality.Step1RegularityGUE
import RBM2D.Universality.GUEPhase.Drift
import RBM2D.Universality.GUETranslation
import RBM2D.Universality.GUEPhase.EntryTail
import RBM2D.Main.BUniv
import RBM2D.Universality.GUEPhase.Proc
import RBM2D.Universality.GUEPhase.BootstrapAt
import RBM2D.Universality.GUEPhase.Eq729A
import RBM2D.Universality.GUEPhase.DuhamelA
import RBM2D.Universality.GUEPhase.HypA
import RBM2D.Universality.GUEPhase.DuhamelB
import RBM2D.Universality.GUEPhase.Eq729B
import RBM2D.Universality.GUEPhase.EntryGrid
import RBM2D.Universality.GUEPhase.BoundsA
import RBM2D.Universality.GUEPhase.DuhamelC
import RBM2D.Universality.GUEPhase.HypB
import RBM2D.Universality.GUEPhase.RandomLayerA
import RBM2D.Universality.GUEPhase.LLTransfer
import RBM2D.Universality.GUEPhase.PathBounds
import RBM2D.Universality.GUEPhase.RandomLayerB
import RBM2D.Main.BUnivHolds

/-! Hard axiom audit of the whole library: see `RBM2D.Test.Axioms`. -/
#assert_rbm_axioms
