import RBM2D.Basic
import RBM2D.Test.Axioms
import RBM2D.Test.Numeric
import RBM2D.Defs.Block
import RBM2D.Defs.Dist
import RBM2D.Defs.Domination
import RBM2D.Defs.Model
import RBM2D.Defs.StochDom
import RBM2D.Propagator.Basic
import RBM2D.Propagator.Bounds
import RBM2D.Propagator.Symbol
import RBM2D.Propagator.Elliptic
import RBM2D.Propagator.Momentum
import RBM2D.Propagator.Shells
import RBM2D.Propagator.GeomSum
import RBM2D.Propagator.Dyadic
import RBM2D.Propagator.ZeroMode
import RBM2D.Propagator.Harmonic
import RBM2D.Propagator.LatticeSum
import RBM2D.Propagator.LogIntegral
import RBM2D.Propagator.ContinuumSymbol
import RBM2D.Propagator.Deriv
import RBM2D.Propagator.Contour
import RBM2D.Propagator.Decay
import RBM2D.Propagator.Cutoff
import RBM2D.Propagator.AbelSum
import RBM2D.Propagator.SymbolDiff
import RBM2D.Propagator.SymbolReciprocalDiff
import RBM2D.Propagator.SymbolReciprocalDiff2
import RBM2D.Propagator.SymbolReciprocalDiff2Bound
import RBM2D.Propagator.SymbolDenomAnnulus
import RBM2D.Propagator.SymbolShiftAnnulus
import RBM2D.Propagator.SymbolReciprocalAnnulusBound
import RBM2D.Propagator.SymbolAnnulusNumerator
import RBM2D.Propagator.SymbolLowShell
import RBM2D.Propagator.SymbolLowShellE2
import RBM2D.Propagator.SymbolCutoffShell
import RBM2D.Propagator.NormalizedFrequency
import RBM2D.Propagator.NormalizedCutoffShell
import RBM2D.Propagator.PhysicalShellDenominator
import RBM2D.Propagator.PhysicalShellNumerator
import RBM2D.Propagator.NormalizedCutoffSecondDiff
import RBM2D.Propagator.NormalizedCutoffDiff
import RBM2D.Propagator.NormalizedCutoffFlat
import RBM2D.Propagator.NormalizedCutoffOuterFlat
import RBM2D.Propagator.NormalizedRadiusSecondDiff
import RBM2D.Propagator.NormalizedRadiusNoFold
import RBM2D.Propagator.NormalizedRadiusFoldCorrection
import RBM2D.Propagator.NormalizedCutoffFoldBound
import RBM2D.Propagator.PeriodizeShells
import RBM2D.Propagator.PeriodizeTail
import RBM2D.Propagator.PeriodizeConvergence
import RBM2D.Propagator.PeriodizeShift
import RBM2D.Propagator.PeriodizeDescend
import RBM2D.Propagator.PeriodizeStencil
import RBM2D.Propagator.PeriodizeDelta
import RBM2D.Propagator.PeriodizeTorusStencil
import RBM2D.Propagator.PeriodizeResolventBridge
import RBM2D.Propagator.PeriodizeFourierDelta
import RBM2D.Propagator.PeriodizeIntegrand
import RBM2D.Propagator.FiniteDiff
import RBM2D.Propagator.DerivBounds
import RBM2D.Delocalization
import RBM2D.Gauss.Envelope
import RBM2D.Gauss.Stein
import RBM2D.Gauss.SteinMatrix
import RBM2D.Gauss.Model
import RBM2D.Gauss.SteinConcrete
import RBM2D.Gauss.Domination
import RBM2D.Gauss.MomentBridge
import RBM2D.Gauss.MomentTimeCont
import RBM2D.Gauss.FlowTimeCont
import RBM2D.Gauss.GreenTimeCont
import RBM2D.Gauss.LoopTimeCont
import RBM2D.Gauss.LoopSampleCont
import RBM2D.Gauss.LoopEnvelope
import RBM2D.Gauss.LoopEnvelopeSharp
import RBM2D.Gauss.LoopMomentCont
import RBM2D.Gauss.SpectralWindow
import RBM2D.Gauss.SpectralAlgebra
import RBM2D.Gauss.SpectralDerivative
import RBM2D.Gauss.FlowDerivative
import RBM2D.Gauss.GreenDerivative
import RBM2D.Gauss.LoopDerivative
import RBM2D.Gauss.LoopCoordinateDerivative
import RBM2D.Gauss.GreenCoordinateSecondDerivative
import RBM2D.Gauss.LoopCoordinateSecondDerivative
import RBM2D.Gauss.LoopCoordinateDerivativeBounds
import RBM2D.Gauss.LoopCoordinateIntegrability
import RBM2D.Gauss.LoopCoordinateStein
import RBM2D.Gauss.LoopCoordinateSteinSum
import RBM2D.Gauss.LoopFlowCoordinateChain
import RBM2D.Gauss.LoopFlowSteinExpectation
import RBM2D.Gauss.LoopFlowDerivativeEnvelope
import RBM2D.Gauss.LoopExpectationDerivative
import RBM2D.Gauss.LoopSpectralDriftCuts
import RBM2D.Gauss.LoopSpectralDriftExpectation
import RBM2D.Gauss.LoopGeneratorSamplewise
import RBM2D.Gauss.LoopGeneratorExpectation
import RBM2D.Gauss.LoopInitialValue
import RBM2D.Gauss.LoopInitialValueScalar
import RBM2D.Gauss.LoopInitialValueProjectionWords
import RBM2D.Gauss.LoopInitialValueEmpty
import RBM2D.Gauss.LoopInitialValueSupport
import RBM2D.Analysis.Bootstrap
import RBM2D.Analysis.MomentGronwallBase
import RBM2D.Analysis.MomentClosing
import RBM2D.Analysis.MomentClosingSup
import RBM2D.Hierarchy.Loops
import RBM2D.Hierarchy.WardResolvent
import RBM2D.Hierarchy.Operations
import RBM2D.Hierarchy.OperationsPair
import RBM2D.Hierarchy.OperationsPairWord
import RBM2D.Hierarchy.ContractionBasic
import RBM2D.Hierarchy.ContractionDirections
import RBM2D.Hierarchy.ContractionSum
import RBM2D.Hierarchy.ContractionUnused
import RBM2D.Hierarchy.ContractionCutWords
import RBM2D.Hierarchy.ContractionDrift
import RBM2D.Hierarchy.ContractionSecondLoop
import RBM2D.Hierarchy.ContractionSecondLoopReverse
import RBM2D.Hierarchy.ContractionSecondLoopSameEdge
import RBM2D.Hierarchy.ContractionSecondLoopSameEdgeWord
import RBM2D.Hierarchy.ContractionSecondLoopSameEdgeCut
import RBM2D.Hierarchy.ContractionSecondLoopPositionSum
import RBM2D.Hierarchy.ContractionEdgeSplits
import RBM2D.Hierarchy.ContractionPairSplits
import RBM2D.Hierarchy.ContractionFirstDerivativePositionSum
import RBM2D.Hierarchy.ContractionSecondDerivativePositionSum
import RBM2D.Hierarchy.ContractionSecondDerivativeTraceSum
import RBM2D.Hierarchy.ContractionPositionLoopBridge
import RBM2D.Hierarchy.ContractionSameEdgePositionCut
import RBM2D.Hierarchy.ContractionPairPositionCut
import RBM2D.Hierarchy.ContractionSecondLoopAllCuts
import RBM2D.Hierarchy.ContractionSecondLoopExpectedCuts
import RBM2D.Hierarchy.LoopHierarchyGenerator
import RBM2D.Hierarchy.LoopHierarchyIntegral
import RBM2D.Hierarchy.LoopHierarchyCutContinuity
import RBM2D.Hierarchy.LoopHierarchyIntegralZero

/-! Hard axiom audit of the whole library: see `RBM2D.Test.Axioms`. -/
#assert_rbm_axioms
