/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import RBM2D.Gauss.Model
import Mathlib.Analysis.Matrix.MeasurableSpace
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Independence.ZeroOne
import Mathlib.Probability.Process.Filtration

/-!
# The grid walk: carrier, filtration, independent increments and the transfer law

The grid walk `H_{u_k} = √s X_0 + √Δ Σ_{i=1}^k X_i` is built from independent draws of the
sequence-level Gaussian sample `Sizes.seqP d`.  The transfer law says that its one-time law is
the law of `Sizes.seqHflow d n u_k` for the grid time `u_k = s + kΔ`.  The proof is
coordinatewise: at each coordinate `c : Sizes.SeqCoord d` the walk is a centred Gaussian of
variance `u_k * seqGvar c`; the matrix is then a measurable image (`Sizes.seqXmat d n`) of the
two equal coordinate laws.
-/

noncomputable section

namespace RBM.Path

open MeasureTheory ProbabilityTheory Filter Matrix RBM RBM.Gauss
open scoped NNReal ENNReal

variable (d : Sizes)

/-- One independent full draw of the sequence-level Gaussian sample per grid step. -/
abbrev PathΩ : Type := ℕ → Sizes.SeqΩ d

/-- The grid measure: independent copies of `Sizes.seqP d`, one per grid step. -/
def pathP : Measure (PathΩ d) := Measure.infinitePi fun _ : ℕ => Sizes.seqP d

/-- The coordinate filtration: `filt d k` is generated by the draws `0, …, k`. -/
def filt : Filtration ℕ (inferInstance : MeasurableSpace (PathΩ d)) :=
  MeasureTheory.Filtration.piLE

/-- Grid spacing `Δ = (t - s)/K` at size index `n`. -/
def gridStep (s t : ℕ → ℝ) (K : ℕ → ℕ) (n : ℕ) : ℝ := (t n - s n) / K n

/-- Grid time `u_k = s + k Δ` at size index `n`. -/
def gridTime (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) : ℝ := s n + k * gridStep s t K n

/-- The grid walk `H_{u_k} = √s X_0 + √Δ Σ_{i=1}^k X_i` at size index `n`. -/
def pathH (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (ω : PathΩ d) :
    Matrix (Idx (d.L n) (d.W n)) (Idx (d.L n) (d.W n)) ℂ :=
  (Real.sqrt (s n) : ℂ) • Sizes.seqXmat d n (ω 0)
    + (Real.sqrt (gridStep s t K n) : ℂ) • ∑ i ∈ Finset.Icc 1 k, Sizes.seqXmat d n (ω i)

/-- **Transfer law**: each grid time has the law of the single-time model at that time. -/
def TransferLaw : Prop :=
  ∀ (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ), 0 ≤ s n → s n ≤ t n → K n ≠ 0 →
    (pathP d).map (pathH d s t K n k) =
      (Sizes.seqP d).map (Sizes.seqHflow d n (gridTime s t K n k))

/-! ### The grid measure and the grid times -/

/-- The grid measure is a probability measure. -/
instance isProbabilityMeasure_pathP : IsProbabilityMeasure (pathP d) := by
  unfold pathP; infer_instance

/-- The last grid time is `t`. -/
theorem gridTime_last (s t : ℕ → ℝ) (K : ℕ → ℕ) (n : ℕ) (hK : K n ≠ 0) :
    gridTime s t K n (K n) = t n := by
  have hK' : (K n : ℝ) ≠ 0 := Nat.cast_ne_zero.2 hK
  unfold gridTime gridStep
  rw [mul_div_cancel₀ _ hK']
  ring

/-! ### The grid walk is Hermitian, measurable and adapted -/

/-- The grid walk is Hermitian. -/
theorem pathH_isHermitian (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (ω : PathΩ d) :
    (pathH d s t K n k ω).IsHermitian := by
  have h0 : (Sizes.seqXmat d n (ω 0))ᴴ = Sizes.seqXmat d n (ω 0) :=
    Sizes.seqXmat_isHermitian d n (ω 0)
  have hsum : (∑ i ∈ Finset.Icc 1 k, Sizes.seqXmat d n (ω i))ᴴ
      = ∑ i ∈ Finset.Icc 1 k, Sizes.seqXmat d n (ω i) := by
    rw [conjTranspose_sum]
    exact Finset.sum_congr rfl fun i _ => Sizes.seqXmat_isHermitian d n (ω i)
  change (pathH d s t K n k ω)ᴴ = pathH d s t K n k ω
  unfold pathH
  rw [conjTranspose_add, conjTranspose_smul, conjTranspose_smul,
    show star (Real.sqrt (s n) : ℂ) = (Real.sqrt (s n) : ℂ) from Complex.conj_ofReal _,
    show star (Real.sqrt (gridStep s t K n) : ℂ) = (Real.sqrt (gridStep s t K n) : ℂ)
      from Complex.conj_ofReal _,
    h0, hsum]

/-- Entries of `Sizes.seqXmat d n` are measurable (`measurable_Xentry` composed with
`measurable_slice`). -/
private lemma measurable_seqXentry (n : ℕ) (i j : Idx (d.L n) (d.W n)) :
    Measurable fun ω : Sizes.SeqΩ d => Sizes.seqXmat d n ω i j :=
  (measurable_Xentry (d.L n) (d.W n) i j).comp (Sizes.measurable_slice d n)

/-- Entrywise formula for the walk. -/
private lemma pathH_apply (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ)
    (i j : Idx (d.L n) (d.W n)) (ω : PathΩ d) :
    pathH d s t K n k ω i j
      = (Real.sqrt (s n) : ℂ) * Sizes.seqXmat d n (ω 0) i j
        + (Real.sqrt (gridStep s t K n) : ℂ)
          * ∑ l ∈ Finset.Icc 1 k, Sizes.seqXmat d n (ω l) i j := by
  simp [pathH, Matrix.add_apply, Matrix.smul_apply, Matrix.sum_apply, Finset.mul_sum]

/-- The entries of the grid walk are measurable. -/
theorem measurable_pathH (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (i j : Idx (d.L n) (d.W n)) :
    Measurable fun ω : PathΩ d => pathH d s t K n k ω i j := by
  have heq : (fun ω : PathΩ d => pathH d s t K n k ω i j) =
      fun ω => (Real.sqrt (s n) : ℂ) * Sizes.seqXmat d n (ω 0) i j
        + (Real.sqrt (gridStep s t K n) : ℂ)
          * ∑ l ∈ Finset.Icc 1 k, Sizes.seqXmat d n (ω l) i j :=
    funext fun ω => pathH_apply d s t K n k i j ω
  rw [heq]
  apply Measurable.add
  · exact ((measurable_seqXentry d n i j).comp (measurable_pi_apply 0)).const_mul _
  · apply Measurable.const_mul
    exact Finset.measurable_sum _ fun l _ =>
      (measurable_seqXentry d n i j).comp (measurable_pi_apply l)

/-- The entries of the grid walk are adapted to the coordinate filtration. -/
theorem pathH_adapted (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (i j : Idx (d.L n) (d.W n)) :
    StronglyMeasurable[filt d k] (fun ω : PathΩ d => pathH d s t K n k ω i j) := by
  rw [stronglyMeasurable_iff_measurable]
  have heq : (fun ω : PathΩ d => pathH d s t K n k ω i j) =
      fun ω => (Real.sqrt (s n) : ℂ) * Sizes.seqXmat d n (ω 0) i j
        + (Real.sqrt (gridStep s t K n) : ℂ)
          * ∑ l ∈ Finset.Icc 1 k, Sizes.seqXmat d n (ω l) i j :=
    funext fun ω => pathH_apply d s t K n k i j ω
  rw [heq]
  have hmeas : ∀ l : ℕ, l ≤ k → Measurable[filt d k] (fun ω : PathΩ d => ω l) := by
    intro l hl
    have : (fun ω : PathΩ d => ω l)
        = (fun g : Set.Iic k → Sizes.SeqΩ d => g ⟨l, hl⟩)
          ∘ (Preorder.restrictLe (π := fun _ : ℕ => Sizes.SeqΩ d) k) := rfl
    rw [this]
    exact (measurable_pi_apply (⟨l, hl⟩ : Set.Iic k)).comp
      (comap_measurable (Preorder.restrictLe (π := fun _ : ℕ => Sizes.SeqΩ d) k))
  apply Measurable.add
  · exact ((measurable_seqXentry d n i j).comp (hmeas 0 (by omega))).const_mul _
  · apply Measurable.const_mul
    exact Finset.measurable_sum _ fun l hl =>
      (measurable_seqXentry d n i j).comp
        (hmeas l (by simp only [Finset.mem_Icc] at hl; omega))

/-! ### Increment independence and law -/

/-- The `k`-th increment `ω ↦ ω (k+1)` is independent of the coordinate filtration `filt d k`. -/
theorem indep_incr (k : ℕ) :
    Indep (MeasurableSpace.comap (fun ω : PathΩ d => ω (k + 1)) inferInstance) (filt d k)
      (pathP d) := by
  have hI : iIndepFun (fun i : ℕ => (fun ω : PathΩ d => ω i)) (pathP d) :=
    iIndepFun_infinitePi (X := fun _ : ℕ => (id : Sizes.SeqΩ d → Sizes.SeqΩ d))
      (mX := fun _ => measurable_id)
  have hIndep : iIndep
      (fun n : ℕ => MeasurableSpace.comap (fun ω : PathΩ d => ω n) inferInstance)
      (pathP d) := (iIndepFun_iff_iIndep
        (fun _ : ℕ => (inferInstance : MeasurableSpace (Sizes.SeqΩ d)))
        (fun i ω => ω i) (pathP d)).mp hI
  have hle : ∀ n : ℕ, MeasurableSpace.comap (fun ω : PathΩ d => ω n) inferInstance
      ≤ (inferInstance : MeasurableSpace (PathΩ d)) :=
    fun n => le_iSup (fun n => MeasurableSpace.comap (fun ω : PathΩ d => ω n) inferInstance) n
  have hsplit := indep_biSup_compl hle hIndep (Set.Iic k)
  have hfilt : filt d k
      = ⨆ n ∈ Set.Iic k, MeasurableSpace.comap (fun ω : PathΩ d => ω n) inferInstance := by
    have hshow : filt d k =
        (inferInstance : MeasurableSpace (↥(Set.Iic k) → Sizes.SeqΩ d)).comap
          (Preorder.restrictLe (π := fun _ : ℕ => Sizes.SeqΩ d) k) := rfl
    have hpi : (inferInstance : MeasurableSpace (↥(Set.Iic k) → Sizes.SeqΩ d))
        = ⨆ a : ↥(Set.Iic k),
            MeasurableSpace.comap (fun g : ↥(Set.Iic k) → Sizes.SeqΩ d => g a) inferInstance :=
      rfl
    rw [hshow, hpi, MeasurableSpace.comap_iSup, iSup_subtype]
    simp only [MeasurableSpace.comap_comp]
    apply iSup_congr
    intro i
    apply iSup_congr
    intro _
    rfl
  rw [hfilt]
  have hmono : MeasurableSpace.comap (fun ω : PathΩ d => ω (k + 1)) inferInstance
      ≤ ⨆ n ∈ (Set.Iic k)ᶜ, MeasurableSpace.comap (fun ω : PathΩ d => ω n) inferInstance := by
    have hmem : (k + 1) ∈ (Set.Iic k)ᶜ := by simp
    exact le_biSup (fun n => MeasurableSpace.comap (fun ω : PathΩ d => ω n) inferInstance) hmem
  exact indep_of_indep_of_le_left hsplit.symm hmono

/-- The law of a single increment is `Sizes.seqP d`. -/
theorem map_incr (k : ℕ) :
    (pathP d).map (fun ω : PathΩ d => ω (k + 1)) = Sizes.seqP d :=
  MeasureTheory.Measure.infinitePi_map_eval _ (k + 1)

/-! ### The transfer law

`pathH` collapses to `Sizes.seqXmat d n` evaluated at a real-linear combination of the raw
draws; the law of this combination is computed coordinatewise. -/

section AlgebraicIdentities

variable {d}

private lemma slice_add (n : ℕ) (ω ν : Sizes.SeqΩ d) :
    Sizes.slice d n (ω + ν) = Sizes.slice d n ω + Sizes.slice d n ν := rfl

private lemma slice_smul (n : ℕ) (a : ℝ) (ω : Sizes.SeqΩ d) :
    Sizes.slice d n (a • ω) = a • Sizes.slice d n ω := rfl

private lemma slice_sum {ι : Type*} (n : ℕ) (S : Finset ι) (ω : ι → Sizes.SeqΩ d) :
    Sizes.slice d n (∑ l ∈ S, ω l) = ∑ l ∈ S, Sizes.slice d n (ω l) := by
  funext c
  simp [Sizes.slice, Finset.sum_apply]

/-- Additivity of `Sizes.seqXmat d n`. -/
private lemma seqXmat_add (n : ℕ) (ω ν : Sizes.SeqΩ d) :
    Sizes.seqXmat d n (ω + ν) = Sizes.seqXmat d n ω + Sizes.seqXmat d n ν := by
  unfold Sizes.seqXmat
  rw [slice_add, Xmat_add]

/-- Homogeneity of `Sizes.seqXmat d n`. -/
private lemma seqXmat_smul (n : ℕ) (a : ℝ) (ω : Sizes.SeqΩ d) :
    Sizes.seqXmat d n (a • ω) = a • Sizes.seqXmat d n ω := by
  unfold Sizes.seqXmat
  rw [slice_smul, Xmat_smul]

/-- `Sizes.seqXmat d n` commutes with finite sums. -/
private lemma seqXmat_sum {ι : Type*} (n : ℕ) (S : Finset ι) (ω : ι → Sizes.SeqΩ d) :
    Sizes.seqXmat d n (∑ l ∈ S, ω l) = ∑ l ∈ S, Sizes.seqXmat d n (ω l) := by
  unfold Sizes.seqXmat
  rw [slice_sum]
  exact map_sum (Xlinear (d.L n) (d.W n)) (fun l => Sizes.slice d n (ω l)) S

/-- Real scalars act on complex matrices through their coercion. -/
private lemma real_smul_matrix' {m : Type*} (r : ℝ) (M : Matrix m m ℂ) :
    r • M = (r : ℂ) • M := by
  ext i j
  simp [Complex.real_smul]

end AlgebraicIdentities

section OneDimensionalGaussianSum

/-- **The Icc-sum of an iid centred Gaussian family is Gaussian with added variance.** A pure
probability fact. -/
private lemma sumIcc_map_gaussianReal {Ω' : Type*} [MeasurableSpace Ω'] {μ' : Measure Ω'}
    [IsProbabilityMeasure μ'] {Y : ℕ → Ω' → ℝ} (hYm : ∀ i, Measurable (Y i))
    (hY : iIndepFun Y μ') {w : ℝ≥0} (hYd : ∀ i, μ'.map (Y i) = gaussianReal 0 w) (k : ℕ) :
    μ'.map (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) = gaussianReal 0 (k • w) := by
  induction k with
  | zero =>
      have hEmpty : Finset.Icc 1 0 = (∅ : Finset ℕ) := Finset.Icc_eq_empty (by omega)
      simp only [hEmpty, Finset.sum_empty]
      rw [Measure.map_const, measure_univ, one_smul, zero_smul, gaussianReal_zero_var]
  | succ k ih =>
      have hnotmem : (k + 1) ∉ Finset.Icc 1 k := by simp
      have hins : Finset.Icc 1 (k + 1) = insert (k + 1) (Finset.Icc 1 k) := by
        ext i; simp only [Finset.mem_Icc, Finset.mem_insert]; omega
      have hfun : (fun ω => ∑ i ∈ Finset.Icc 1 (k + 1), Y i ω)
          = (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) + Y (k + 1) := by
        funext ω
        rw [hins, Finset.sum_insert hnotmem, add_comm]
        rfl
      rw [hfun]
      have hsummeas : Measurable (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) :=
        Finset.measurable_sum _ fun i _ => hYm i
      have hlaw1 : HasLaw (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) (gaussianReal 0 (k • w)) μ' :=
        ⟨hsummeas.aemeasurable, ih⟩
      have hlaw2 : HasLaw (Y (k + 1)) (gaussianReal 0 w) μ' :=
        ⟨(hYm (k + 1)).aemeasurable, hYd (k + 1)⟩
      have hindep : IndepFun (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) (Y (k + 1)) μ' := by
        have h := hY.indepFun_finsetSum_of_notMem hYm hnotmem
        have heq : (∑ j ∈ Finset.Icc 1 k, Y j) = fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω := by
          funext ω; simp [Finset.sum_apply]
        rwa [heq] at h
      have hres := gaussianReal_add_gaussianReal_of_indepFun hindep hlaw1 hlaw2
      rw [hres, add_zero, ← succ_nsmul]

/-- **The two-scale weighted sum lemma**.  With `a` scaling the base draw `Y 0` and `b` scaling
each of the `k`
increments `Y 1, …, Y k`, the total variance is `a² w + k (b² w)`. -/
private lemma weightedSum_map_gaussianReal {Ω' : Type*} [MeasurableSpace Ω'] {μ' : Measure Ω'}
    [IsProbabilityMeasure μ'] {Y : ℕ → Ω' → ℝ} (hYm : ∀ i, Measurable (Y i))
    (hY : iIndepFun Y μ') {w : ℝ≥0} (hYd : ∀ i, μ'.map (Y i) = gaussianReal 0 w)
    (a b : ℝ) (k : ℕ) :
    μ'.map (fun ω => a * Y 0 ω + b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
      = gaussianReal 0
          (NNReal.mk (a ^ 2) (sq_nonneg a) * w + k • (NNReal.mk (b ^ 2) (sq_nonneg b) * w)) := by
  classical
  have hindep : IndepFun (fun ω => a * Y 0 ω) (fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω) μ' := by
    have h0 : IndepFun (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) (Y 0) μ' := by
      have h := hY.indepFun_finsetSum_of_notMem hYm (s := Finset.Icc 1 k) (i := 0) (by simp)
      have heq : (∑ j ∈ Finset.Icc 1 k, Y j) = fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω := by
        funext ω; simp [Finset.sum_apply]
      rwa [heq] at h
    exact h0.symm.comp (φ := (a * ·)) (ψ := (b * ·)) (by fun_prop) (by fun_prop)
  have hlaw0 : HasLaw (fun ω => a * Y 0 ω)
      (gaussianReal 0 (NNReal.mk (a ^ 2) (sq_nonneg a) * w)) μ' := by
    refine ⟨by fun_prop, ?_⟩
    have : (fun ω => a * Y 0 ω) = (a * ·) ∘ Y 0 := rfl
    rw [this, ← Measure.map_map (by fun_prop) (hYm 0), hYd 0, gaussianReal_map_const_mul,
      mul_zero]
  have hsummeas : Measurable (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) :=
    Finset.measurable_sum _ fun i _ => hYm i
  have hlawsum : μ'.map (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) = gaussianReal 0 (k • w) :=
    sumIcc_map_gaussianReal hYm hY hYd k
  have hlaw1 : HasLaw (fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
      (gaussianReal 0 (NNReal.mk (b ^ 2) (sq_nonneg b) * (k • w))) μ' := by
    refine ⟨by fun_prop, ?_⟩
    have heq : (fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
        = (b * ·) ∘ (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) := rfl
    rw [heq, ← Measure.map_map (by fun_prop) hsummeas, hlawsum, gaussianReal_map_const_mul,
      mul_zero]
  have hgoal_eq : (fun ω => a * Y 0 ω + b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
      = (fun ω => a * Y 0 ω) + fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω := rfl
  rw [hgoal_eq]
  have hres := gaussianReal_add_gaussianReal_of_indepFun hindep hlaw0 hlaw1
  rw [hres, add_zero]
  congr 1
  rw [nsmul_eq_mul, nsmul_eq_mul]
  apply NNReal.coe_injective
  push_cast
  ring

end OneDimensionalGaussianSum

section CombinedIdentities

variable {d}

/-- `pathH` collapses to `seqXmat` evaluated at the real-linear grid combination of the raw
draws.  Uses `seqXmat_add`, `seqXmat_smul`,
`seqXmat_sum` above. -/
private lemma pathH_eq_seqXmat_combined (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (ω : PathΩ d) :
    pathH d s t K n k ω
      = Sizes.seqXmat d n ((Real.sqrt (s n) : ℝ) • ω 0
          + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) := by
  rw [seqXmat_add, seqXmat_smul, seqXmat_smul, seqXmat_sum, real_smul_matrix',
    real_smul_matrix']
  rfl

/-- `seqHflow` collapses to `seqXmat` evaluated at the real scaling `√u • ω'` (from
`Sizes.seqHflow_eq_smul` and `seqXmat_smul`). -/
private lemma seqHflow_eq_seqXmat_smul (n : ℕ) (u : ℝ) (ω' : Sizes.SeqΩ d) :
    Sizes.seqHflow d n u ω' = Sizes.seqXmat d n ((Real.sqrt u : ℝ) • ω') := by
  rw [Sizes.seqHflow_eq_smul, seqXmat_smul, real_smul_matrix']

private lemma measurable_seqXmat (n : ℕ) : Measurable (Sizes.seqXmat d n) :=
  measurable_pi_iff.2 fun i => measurable_pi_iff.2 fun j => measurable_seqXentry d n i j

private lemma measurable_combined (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) :
    Measurable (fun ω : PathΩ d => (Real.sqrt (s n) : ℝ) • ω 0
      + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) := by
  have h1 : Measurable (fun ω : PathΩ d => ω 0) := measurable_pi_apply 0
  have h2 : Measurable (fun ω : PathΩ d => ∑ i ∈ Finset.Icc 1 k, ω i) :=
    Finset.measurable_sum _ fun i _ => measurable_pi_apply i
  exact (h1.const_smul (Real.sqrt (s n))).add (h2.const_smul (Real.sqrt (gridStep s t K n)))

private lemma measurable_smul_SeqΩ (u : ℝ) :
    Measurable (fun ω' : Sizes.SeqΩ d => (Real.sqrt u : ℝ) • ω') :=
  measurable_id.const_smul (Real.sqrt u)

end CombinedIdentities

section TheTransferLemma

variable {d}

/-- **The column law.** At a fixed raw coordinate `c`, the `k+1`-fold grid combination of iid
copies of `gaussianReal 0 (seqGvar d c)` is Gaussian with the added variance. -/
private lemma map_column_eq (c : Sizes.SeqCoord d) (a b : ℝ) (k : ℕ) :
    (Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar d c))).map
        (fun y : ℕ → ℝ => a * y 0 + b * ∑ i ∈ Finset.Icc 1 k, y i)
      = gaussianReal 0 (NNReal.mk (a ^ 2) (sq_nonneg a) * Sizes.seqGvar d c
          + k • (NNReal.mk (b ^ 2) (sq_nonneg b) * Sizes.seqGvar d c)) := by
  have hY : iIndepFun (fun i : ℕ => (fun y : ℕ → ℝ => y i))
      (Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar d c))) :=
    iIndepFun_infinitePi (X := fun _ : ℕ => (id : ℝ → ℝ)) (mX := fun _ => measurable_id)
  have hYm : ∀ i : ℕ, Measurable (fun y : ℕ → ℝ => y i) := fun i => measurable_pi_apply i
  have hYd : ∀ i : ℕ, (Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar d c))).map
      (fun y : ℕ → ℝ => y i) = gaussianReal 0 (Sizes.seqGvar d c) :=
    fun i => Measure.infinitePi_map_eval _ i
  exact weightedSum_map_gaussianReal hYm hY hYd a b k

/-- The nested product over `SeqCoord d` first, then over the grid index `ℕ`. -/
private def pathP' (d : Sizes) : Measure (Sizes.SeqCoord d → ℕ → ℝ) :=
  Measure.infinitePi
    (fun c : Sizes.SeqCoord d =>
      Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar d c)))

/-- The composite reindexing map `(SeqCoord d → ℕ → ℝ) → PathΩ d`: uncurry, swap the two axes,
curry back. -/
private def swapEquiv (d : Sizes) : (Sizes.SeqCoord d → ℕ → ℝ) → PathΩ d :=
  (MeasurableEquiv.curry ℕ (Sizes.SeqCoord d) ℝ) ∘
    (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord d => ℝ)
      (Equiv.prodComm (Sizes.SeqCoord d) ℕ)) ∘
    (MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm

private lemma measurable_swapEquiv : Measurable (swapEquiv d) :=
  (MeasurableEquiv.curry ℕ (Sizes.SeqCoord d) ℝ).measurable.comp
    ((MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord d => ℝ)
        (Equiv.prodComm (Sizes.SeqCoord d) ℕ)).measurable.comp
      (MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm.measurable)

/-- **The swap identity**.  `pathP' d`, after
reordering the two axes, coincides with `pathP d`.  Chain of `Measure.infinitePi_map_curry_symm`,
`Measure.infinitePi_map_piCongrLeft` and `Measure.infinitePi_map_curry`. -/
private lemma pathP_swap_eq : (pathP' d).map (swapEquiv d) = pathP d := by
  have ha : (pathP' d).map ((MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm)
      = Measure.infinitePi
          (fun p : Sizes.SeqCoord d × ℕ => gaussianReal 0 (Sizes.seqGvar d p.1)) :=
    Measure.infinitePi_map_curry_symm
      (μ := fun (c : Sizes.SeqCoord d) (_ : ℕ) => gaussianReal 0 (Sizes.seqGvar d c))
  have hb : (Measure.infinitePi
        (fun p : Sizes.SeqCoord d × ℕ => gaussianReal 0 (Sizes.seqGvar d p.1))).map
      (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord d => ℝ)
        (Equiv.prodComm (Sizes.SeqCoord d) ℕ))
      = Measure.infinitePi
          (fun p : ℕ × Sizes.SeqCoord d => gaussianReal 0 (Sizes.seqGvar d p.2)) :=
    Measure.infinitePi_map_piCongrLeft
      (μ := fun p : ℕ × Sizes.SeqCoord d => gaussianReal 0 (Sizes.seqGvar d p.2))
      (Equiv.prodComm (Sizes.SeqCoord d) ℕ)
  have hc : (Measure.infinitePi
        (fun p : ℕ × Sizes.SeqCoord d => gaussianReal 0 (Sizes.seqGvar d p.2))).map
      (MeasurableEquiv.curry ℕ (Sizes.SeqCoord d) ℝ) = pathP d :=
    Measure.infinitePi_map_curry
      (μ := fun (_ : ℕ) (c : Sizes.SeqCoord d) => gaussianReal 0 (Sizes.seqGvar d c))
  change (pathP' d).map ((MeasurableEquiv.curry ℕ (Sizes.SeqCoord d) ℝ) ∘
      (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord d => ℝ)
        (Equiv.prodComm (Sizes.SeqCoord d) ℕ)) ∘
      (MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm) = pathP d
  rw [← Measure.map_map (by fun_prop) (by fun_prop), ← Measure.map_map (by fun_prop) (by fun_prop),
    ha, hb, hc]

/-- The pointwise formula for the swap map. -/
private lemma swapEquiv_apply (X : Sizes.SeqCoord d → ℕ → ℝ) (i : ℕ) (c : Sizes.SeqCoord d) :
    swapEquiv d X i c = X c i := by
  change (MeasurableEquiv.curry ℕ (Sizes.SeqCoord d) ℝ)
      ((MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord d => ℝ)
          (Equiv.prodComm (Sizes.SeqCoord d) ℕ))
        ((MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm X)) i c = X c i
  rw [MeasurableEquiv.coe_curry]
  change (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord d => ℝ)
      (Equiv.prodComm (Sizes.SeqCoord d) ℕ))
      ((MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm X) (i, c) = X c i
  have key := MeasurableEquiv.piCongrLeft_apply_apply (Equiv.prodComm (Sizes.SeqCoord d) ℕ)
    (β := fun _ : ℕ × Sizes.SeqCoord d => ℝ)
    ((MeasurableEquiv.curry (Sizes.SeqCoord d) ℕ ℝ).symm X) (c, i)
  rw [show Equiv.prodComm (Sizes.SeqCoord d) ℕ (c, i) = (i, c) from rfl] at key
  rw [key, MeasurableEquiv.coe_curry_symm]
  rfl

/-- **The combined-grid law**.  The `k+1`-fold
grid combination has, at each raw coordinate `c : SeqCoord d`, the Gaussian law of the sum of the
variances contributed by the base draw and by the `k` increments. -/
private lemma map_combined_eq (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) :
    (pathP d).map (fun ω : PathΩ d => (Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i)
      = Measure.infinitePi (fun c : Sizes.SeqCoord d => gaussianReal 0
          (NNReal.mk (Real.sqrt (s n) ^ 2) (sq_nonneg _) * Sizes.seqGvar d c
            + k • (NNReal.mk (Real.sqrt (gridStep s t K n) ^ 2) (sq_nonneg _)
              * Sizes.seqGvar d c))) := by
  have hcomp : (fun ω : PathΩ d => (Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) ∘ (swapEquiv d)
      = (fun X : Sizes.SeqCoord d → ℕ → ℝ => fun c => Real.sqrt (s n) * X c 0
          + Real.sqrt (gridStep s t K n) * ∑ i ∈ Finset.Icc 1 k, X c i) := by
    funext X
    funext c
    simp only [Function.comp_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul, Finset.sum_apply,
      swapEquiv_apply]
  rw [← pathP_swap_eq, Measure.map_map (measurable_combined s t K n k) measurable_swapEquiv,
    hcomp]
  have hfmeas : ∀ c : Sizes.SeqCoord d, Measurable (fun y : ℕ → ℝ => Real.sqrt (s n) * y 0
      + Real.sqrt (gridStep s t K n) * ∑ i ∈ Finset.Icc 1 k, y i) := fun c => by
    have h1 : Measurable (fun y : ℕ → ℝ => y 0) := measurable_pi_apply 0
    have h2 : Measurable (fun y : ℕ → ℝ => ∑ i ∈ Finset.Icc 1 k, y i) :=
      Finset.measurable_sum _ fun i _ => measurable_pi_apply i
    exact (h1.const_mul _).add (h2.const_mul _)
  have hpi := Measure.infinitePi_map_pi
      (μ := fun c : Sizes.SeqCoord d =>
        Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar d c)))
      (f := fun c : Sizes.SeqCoord d => fun y : ℕ → ℝ => Real.sqrt (s n) * y 0
        + Real.sqrt (gridStep s t K n) * ∑ i ∈ Finset.Icc 1 k, y i) hfmeas
  rw [pathP']
  exact hpi.trans (congrArg Measure.infinitePi
    (funext fun c => map_column_eq c (Real.sqrt (s n)) (Real.sqrt (gridStep s t K n)) k))

/-- **The scaled-flow law**.  The law of `√u • ω` on the common sample space has, at each
coordinate, variance
`u` times the original variance. -/
private lemma map_smul_eq (u : ℝ) (hu : 0 ≤ u) :
    (Sizes.seqP d).map (fun ω' : Sizes.SeqΩ d => (Real.sqrt u : ℝ) • ω')
      = Measure.infinitePi
          (fun c : Sizes.SeqCoord d => gaussianReal 0 (NNReal.mk u hu * Sizes.seqGvar d c)) := by
  have hfmeas : ∀ c : Sizes.SeqCoord d, Measurable ((Real.sqrt u : ℝ) * ·) :=
    fun c => by fun_prop
  have h1 : (Sizes.seqP d).map (fun ω' : Sizes.SeqΩ d => fun c => (Real.sqrt u : ℝ) * ω' c)
      = Measure.infinitePi
          (fun c : Sizes.SeqCoord d =>
            (gaussianReal 0 (Sizes.seqGvar d c)).map ((Real.sqrt u : ℝ) * ·)) :=
    Measure.infinitePi_map_pi (μ := fun c : Sizes.SeqCoord d => gaussianReal 0 (Sizes.seqGvar d c))
      (f := fun _ : Sizes.SeqCoord d => ((Real.sqrt u : ℝ) * ·)) hfmeas
  have heq : (fun ω' : Sizes.SeqΩ d => (Real.sqrt u : ℝ) • ω')
      = (fun ω' : Sizes.SeqΩ d => fun c => (Real.sqrt u : ℝ) * ω' c) := by
    funext ω' c; simp [smul_eq_mul]
  rw [heq, h1]
  congr 1
  funext c
  rw [gaussianReal_map_const_mul, mul_zero]
  congr 1
  apply NNReal.coe_injective
  push_cast
  rw [Real.sq_sqrt hu]

end TheTransferLemma

/-- **The transfer lemma**.  The grid walk `pathH` at grid
step `k` has the same law as the one-time flow `Sizes.seqHflow` at the grid time. -/
theorem map_pathH_eq (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (hs : 0 ≤ s n) (hst : s n ≤ t n)
    (hK : K n ≠ 0) :
    (pathP d).map (pathH d s t K n k)
      = (Sizes.seqP d).map (Sizes.seqHflow d n (gridTime s t K n k)) := by
  have hstep : 0 ≤ gridStep s t K n := div_nonneg (by linarith) (Nat.cast_nonneg _)
  have hu : 0 ≤ gridTime s t K n k := by
    have : 0 ≤ (k : ℝ) * gridStep s t K n := mul_nonneg (Nat.cast_nonneg k) hstep
    unfold gridTime; linarith
  have hHeq : pathH d s t K n k = fun ω => Sizes.seqXmat d n ((Real.sqrt (s n) : ℝ) • ω 0
      + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) :=
    funext (pathH_eq_seqXmat_combined s t K n k)
  have hHfloweq : Sizes.seqHflow d n (gridTime s t K n k)
      = fun ω' => Sizes.seqXmat d n ((Real.sqrt (gridTime s t K n k) : ℝ) • ω') :=
    funext (seqHflow_eq_seqXmat_smul n (gridTime s t K n k))
  rw [hHeq, hHfloweq,
    show (fun ω : PathΩ d => Sizes.seqXmat d n ((Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i))
      = Sizes.seqXmat d n ∘ (fun ω => (Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) from rfl,
    show (fun ω' : Sizes.SeqΩ d => Sizes.seqXmat d n ((Real.sqrt (gridTime s t K n k) : ℝ) • ω'))
      = Sizes.seqXmat d n ∘ (fun ω' => (Real.sqrt (gridTime s t K n k) : ℝ) • ω') from rfl,
    ← Measure.map_map (measurable_seqXmat n) (measurable_combined s t K n k),
    ← Measure.map_map (measurable_seqXmat n) (measurable_smul_SeqΩ (gridTime s t K n k)),
    map_combined_eq s t K n k, map_smul_eq (gridTime s t K n k) hu]
  congr 1
  refine congrArg Measure.infinitePi (funext fun c => ?_)
  have hvar : NNReal.mk (Real.sqrt (s n) ^ 2) (sq_nonneg _) * Sizes.seqGvar d c
      + k • (NNReal.mk (Real.sqrt (gridStep s t K n) ^ 2) (sq_nonneg _) * Sizes.seqGvar d c)
      = NNReal.mk (gridTime s t K n k) hu * Sizes.seqGvar d c := by
    have h1 : Real.sqrt (s n) ^ 2 = s n := Real.sq_sqrt hs
    have h2 : Real.sqrt (gridStep s t K n) ^ 2 = gridStep s t K n := Real.sq_sqrt hstep
    apply NNReal.coe_injective
    push_cast
    rw [h1, h2]
    unfold gridTime
    ring
  rw [hvar]

/-- **The transfer law.** -/
theorem transferLaw : TransferLaw d :=
  fun s t K n k hs hst hK => map_pathH_eq d s t K n k hs hst hK

end RBM.Path

end
